### ISSUE TITLE
Should we put this also somewhere else?

### ISSUE THREAD

**Issue by broeder-j** [Tseplyaev/tutorial_notebooks_2019#2]
1. Should we rebase this to a judft_aiida_tutorial repo under judftteam on github, or on iffgit?
2. Or should we put it into aiida-fleur under examples/ tutorials?
@anoopkcn  @Tseplyaev  What do you think?

Advantage of 1. would be that we can collect there also tutorials for aiida-kkr, aiida-spex and co. so there is one place, which one could imbed into a website, since I also assume that judft tutorials in the future deal with several of our codes.

Advantage of 2. would be that we can make the tutorials easily part of the aiida-fleur documentation.

**Comment by Tseplyaev** [comment]
@broeder-j 
I think the option 1 is a better one because in this way it is easier to distribute it independently from the main package.
If we attach the tutorial to aiida-fleur then one needs to take care of constantly updating it (which takes some time).
If we keep it separate, we can just add to the tutorial documentation something like 'this version was tested for AiiDA 1.x.x'.

**Comment by broeder-j** [comment]
I agree.
I went with one, but left it on github, because just forking it was less effort. xD.
You find it now here: https://github.com/JuDFTteam/judft_tutorials
